<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { getApps, getGuides, type AppItem, type Guide } from '../services/content'
const apps=ref<AppItem[]>([]), guides=ref<Guide[]>([]), error=ref(false), installEvent=ref<any>(null)
onMounted(async()=>{try{[apps.value,guides.value]=await Promise.all([getApps(),getGuides()])}catch{error.value=true} window.addEventListener('beforeinstallprompt',(e:any)=>{e.preventDefault();installEvent.value=e})})
async function install(){await installEvent.value?.prompt();installEvent.value=null}
</script>
<template>
 <section class="hero"><div class="orb orb-pink"></div><div class="orb orb-blue"></div><div class="hero-copy"><p class="eyebrow">TU PRÓXIMO PASO EMPIEZA AQUÍ</p><h1>Aprende. Conecta.<br><em>Avanza con seguridad.</em></h1><p class="hero-text">El centro de orientación para descubrir aplicaciones, entender sus reglas y comenzar con una guía clara.</p><div class="hero-actions"><RouterLink class="button" to="/apps/mujeres">Explorar aplicaciones <span>→</span></RouterLink><button v-if="installEvent" class="button button-ghost" @click="install">Instalar app</button></div><div class="trust"><span>✦ Información organizada</span><span>✦ Guías de capacitación</span><span>✦ Acompañamiento</span></div></div><div class="hero-visual"><div class="glass-card card-top"><small>RECOMPENSAS</small><b>Tu esfuerzo<br>tiene valor</b><i>✦</i></div><div class="glass-card card-bottom"><span class="mini-logo">S</span><div><small>ORIENTACIÓN</small><b>Todo más claro</b></div><span>↗</span></div><div class="ring"></div></div></section>
 <section class="quick-section"><div class="section-head"><p class="eyebrow">ENCUENTRA TU CAMINO</p><h2>Todo lo que necesitas,<br><em>en un mismo lugar.</em></h2></div><div class="quick-grid"><RouterLink to="/apps/mujeres" class="quick-card pink"><span>01</span><b>Apps para<br>mujeres</b><i>→</i></RouterLink><RouterLink to="/apps/hombres" class="quick-card blue"><span>02</span><b>Apps para<br>hombres</b><i>→</i></RouterLink><RouterLink to="/guias" class="quick-card violet"><span>03</span><b>Guías y<br>recursos</b><i>→</i></RouterLink><RouterLink to="/ser-agente" class="quick-card light"><span>04</span><b>Quiero ser<br>agente</b><i>→</i></RouterLink></div></section>
 <section class="content-section"><div class="section-row"><div><p class="eyebrow">APLICACIONES</p><h2>Explora opciones<br><em>con información clara.</em></h2></div><RouterLink to="/apps/mujeres" class="text-link">Ver todas →</RouterLink></div><p v-if="error" class="notice">No pudimos cargar el contenido. Intenta nuevamente.</p><div v-else-if="apps.length" class="app-grid"><article v-for="app in apps.slice(0,3)" :key="app.id" class="app-card"><div class="app-art" :style="app.banner_url?{backgroundImage:`url(${app.banner_url})`}:{}"><span>{{ app.name.slice(0,1) }}</span></div><div><p>{{ app.gender==='women'?'Para mujeres':'Para hombres' }}</p><h3>{{ app.name }}</h3><small>{{ app.description || 'Información disponible próximamente.' }}</small><RouterLink :to="`/apps/${app.gender==='women'?'mujeres':'hombres'}`">Conocer más →</RouterLink></div></article></div><div v-else class="empty-state">Aún no hay aplicaciones publicadas. Vuelve pronto.</div></section>
 <section class="steps"><p class="eyebrow">ASÍ DE SIMPLE</p><h2>Empieza en tres pasos.</h2><div><article><span>01</span><b>Explora</b><p>Conoce opciones y elige la que mejor encaje contigo.</p></article><article><span>02</span><b>Infórmate</b><p>Revisa guías, condiciones y formas de trabajo.</p></article><article><span>03</span><b>Conecta</b><p>Accede a los canales oficiales y recibe orientación.</p></article></div></section>
 <section class="training"><div><p class="eyebrow">CAPACÍTATE</p><h2>Aprender es tu<br><em>mejor ventaja.</em></h2><p>Encuentra guías prácticas para comenzar con confianza.</p><RouterLink to="/guias" class="button">Ver guías <span>→</span></RouterLink></div><div class="guide-stack"><article v-for="(guide,i) in guides.slice(0,3)" :key="guide.id"><span>0{{i+1}}</span><b>{{guide.title}}</b><i>↗</i></article><article v-if="!guides.length"><span>01</span><b>Guías de capacitación próximamente</b></article></div></section>
</template>

